###Get service document
http://localhost:4004/odata/v4/CatalogService

###Get service Metdata document
http://localhost:4004/odata/v4/CatalogService/$metadata

###Get all Employee data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet

###POST - Create new Employee
POST http://localhost:4004/odata/v4/CatalogService/Employeeset
Content-Type: application/json

{
    
      "nameFirst": "Reyan",
      "nameMiddle": null,
      "nameLast": "Kurra",
      "nameInitials": null,
      "sex": "M",
      "language": "E",
      "phoneNumber": "7373264592",
      "email": "satish@itelo.info",
      "loginName": "SPRINGS",
      "Currency_code": "USD",
      "salaryAmount": 55549,
      "accountNumber": "111222333",
      "bankId": "510000655",
      "bankName": "My Bank of Antioch"
}

### Get to read the single employee data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/e2002f0f-403d-4839-8a9e-e3b461243c62

### Patch to update employee data
PATCH  http://localhost:4004/odata/v4/CatalogService/EmployeeSet/e2002f0f-403d-4839-8a9e-e3b461243c62
Content-Type: application/json

{
       "salaryAmount": 1000000
}

###Pagination 
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=2&$skip=2

###Get all PO
http://localhost:4004/odata/v4/CatalogService/POs

###Get PO Items and associatioons 
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC28052?$expand=Items,PARTNER_GUID

###Calling an action
POST http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC28052/boost
Content-Type: application/json

{

}

###Get function 
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC28052/largestOrder()

###Get all Business
http://localhost:4004/odata/v4/CatalogService/BusinessPartner

###Getting Product data from CDS View
GET http://localhost:4004/odata/v4/MyService/ProductOrdersSet/74867AD200E41EDBA5D8B06B26EB4052

###Get metadata
GET http://localhost:4004/odata/v4/MyService/$metadata

###Get the lazy loading -- 
GET http://localhost:4004/odata/v4/MyService/ProductOrdersSet/74867AD200E41EDBA5D8B06B26EB4052?$expand=PO_ORDERS

###Complete custom entity which has strcture from DB but logic by our own handling 
http://localhost:4004/odata/v4/MyService/ReadEmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C19787FB

###GEt all Pos using adpater proxy V2
http://localhost:4004/v2/odata/v4/CatalogService/POs
